horizon.target_param_data_ratio: -1
horizon.target_flops: 1e18, 2.15e18, 4.64e18, 1e19
model.depth: 22
optim.device_batch_size: 16

eval.core_metric_every: -1
eval.core_metric_max_per_task: -1
eval.sample_every: -1

# 4 checkpoints every run
log.save_every: -1
log.num_checkpoints: 4

optim.embedding_lr: '${uniform:0.1,1.0}'
optim.unembedding_lr: '${uniform:0.004,0.04}'
optim.weight_decay: '${uniform:0.05,0.5}'
optim.matrix_lr: '${uniform:0.005,0.05}'
optim.scalar_lr: '${uniform:0.1,1.0}'
optim.warmdown_ratio: '${uniform:0.2,0.85}'
optim.final_lr_frac: '${uniform:0.005,0.15}'

log.sweep_id: sweep_5
log.wandb_project: nanochat, nanochat # dummy sweep to get multiple runs
