defaults:
  - eval_schema
  - _self_
  - hydra: base
  - hydra/sweeper/params: null
  - override hydra/launcher: tamia

ckpt: ???
ckpt_root: /home/l/leog/links/scratch/nanochat/logs/outputs
max_per_task: -1
eval_tokens: 41943040  # 80 * 524288
device_batch_size: 16
device_type: ""
